modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/hypherionmc/MaintenanceMode/issues"

[[mods]]
modId="mmode"
version="${file.jarVersion}"
displayName="Maintenance Mode"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://readme.firstdarkdev.xyz/maintenance-mode/introduction/"
logoFile="mmode_icon.png"
#credits="Thanks for this example mod goes to Java"
authors="HypherionSA"
displayTest = "IGNORE_ALL_VERSION"

description='''
Put your server in maintenance mode, while giving only specific people access. Useful for doing work on servers without having people join!
'''

[[dependencies.mmode]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.mmode]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="SERVER"
